hamsterserv/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView
from hamsterserv.admin import hamster_admin, suir_admin, sispro_admin


urlpatterns = [
    path('admin/', include([
        path('1/', suir_admin.urls),
        path('2/', hamster_admin.urls),
        path('3/', sispro_admin.urls),
        ])),
    path('api/', include([
        path('hamster/', include('hamster.urls')),
        path('sispro/', include('sispro.urls')),
        ])),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hamster/', TemplateView.as_view(template_name='hamster/index.html'), name='inicio_hamster'),
    path('', include('suir.urls')),
]

suir/urls.py
from django.urls import path, include
#from rest_framework.routers import DefaultRouter
from suir.views import *


#  Creación del DefaultRouter para que maneje
#  las rutas de los ViewSets

# router = DefaultRouter()

#  Registramos los ViewSets con su segmento de la URL

# router.register(r'anuncios', AnuncioViewSet)
# router.register(r'tablas', TablaViewSet)
# router.register(r'indicadores', IndicadorViewSet)
# router.register(r'enlaces', LinkExternoViewSet)
# router.register(r'publicaciones', PublicacionViewSet)

urlpatterns = [
	# path('', include(router.urls)),
]

suir/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.urls import reverse
from rest_framework.authtoken.models import Token
from django_timestamps.softDeletion import SoftDeletionModel
from django_timestamps.timestamps import TimestampsModel
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

# Función para crear tokens para cada usuario

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):

	if created:
		Token.objects.create(user=instance)


class Anuncio(models.Model):
	"""Clase del modelo Anuncio"""
	titulo = models.CharField('Título', max_length=45)
	imagen = models.ImageField('Imágen', upload_to='suir/anuncios/img/')
	url = models.URLField('URL del sitio', max_length=150)
	activo = models.BooleanField()

	def __str__(self):
		return self.titulo

	class Meta:
		ordering = ['activo', 'titulo']



class Carrusel(SoftDeletionModel):
	""" 
	Modelo Carrusel. Se emplea para administrar las imágenes que se despliegan en el carrusel.
	"""

	imagen = models.ImageField(upload_to='suir/carrusel/img/')
	titulo = models.CharField(max_length=25)
	descripcion = models.CharField(max_length=250)
	activo = models.BooleanField()

	class Meta:
		ordering = ['activo', 'titulo']

	def __str__(self):
		return self.titulo
	
	

class Contacto(SoftDeletionModel):
	"""Clase del modelo Contacto"""
	nombre = models.CharField(max_length=50)
	apellido = models.CharField(max_length=50)
	movil = models.CharField('Móvil', max_length=9, validators=[RegexValidator(regex="[0-9]{4}-[0-9]{4}", message="El valor no es un número telefónico válido.")], help_text="Formato 8888-8888")
	correo = models.EmailField('Correo electrónico')
	cargo = models.ForeignKey('DetalleTabla', on_delete=models.SET_NULL, limit_choices_to=Q(tabla__tabla='cargos'), null=True)
	institucion = models.ForeignKey('Institucion', on_delete=models.CASCADE)
	usuario = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return "%s %s" % (self.nombre, self.apellido)

	class Meta:
		ordering = ['institucion', 'apellido']



class Tabla(TimestampsModel):
	"""Clase para el modelo Tabla"""
	tabla = models.CharField(max_length=25)

	def __str__(self):
		return self.tabla.upper()



class DetalleTabla(TimestampsModel):
	"""Clase para el modelo DetalleTabla"""
	elemento = models.CharField(max_length=45)
	codigo_eq = models.CharField('Código de equivalencia', max_length=15, null=True, blank=True)
	tabla = models.ForeignKey(Tabla, on_delete=models.CASCADE)

	def __str__(self):
		return self.elemento.upper()

	class Meta:
		ordering = ['tabla', 'id']

	
		
class Entidad(SoftDeletionModel):
	"""Clase para el modelo Entidad de Monitoreo de Indicadores"""
	nombre = models.CharField(max_length=45)
	sector = models.ForeignKey(DetalleTabla, on_delete=models.RESTRICT, limit_choices_to=Q(tabla__tabla='sectores'), help_text="Sector social que atiende la entidad.")
	nivel = models.CharField(max_length=45, choices=[('S', 'SECRETARÍA'),('D', 'DIRECCIÓN'),('C', 'COMISIÓN'), ('O', 'OFICINA')])
	enlace = models.BooleanField('Es Enlace')

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = 'Entidades'


class Municipio(models.Model):

	"""
	Clase para el modelo Municipio.
	""" 
	nombre = models.CharField(max_length=50)
	nombre_corto = models.CharField(max_length=10)
	region = models.CharField(max_length=5, choices=[('racs', 'Región Autónoma del Caribe Sur'),('racn', 'Región Autónoma del Caribe Norte')], default='racs')
	area = models.FloatField('Área (Km2)', null=True, help_text="Extensión en Km2")
	poblacion = models.IntegerField('Población aprox.', null=True)

	mpoly = models.MultiPolygonField()

	def __str__(self):
		return self.nombre.upper()

	class Meta:
		ordering = ['nombre']


class Comunidad(models.Model):

	""" 
	Clase para el modelo Comunidad. Empleado como nivel por defecto de desagregación de indicadores.
	"""
	nombre = models.CharField(max_length=150)
	municipio = models.ForeignKey(Municipio, on_delete=models.RESTRICT)
	actividades_ec = models.ManyToManyField(DetalleTabla, related_name='+', help_text='Actividades económicas desarrolladas en la comunidad.', limit_choices_to=Q(tabla__tabla='actividades_ec'))

	location = models.PointField(null=True)

	def __str__(self):
		return "%s-%s" % (self.municipio.nombre_corto.upper(), self.nombre.upper())

	class Meta:
		verbose_name_plural = 'Comunidades'
		ordering = ['municipio', 'nombre']



class Indicador(SoftDeletionModel, TimestampsModel):
	"""Clase para el modelo Indicador"""
	
	titulo = models.CharField('Título', max_length=150)	
	descripcion = models.CharField(max_length=250)
	sector = models.ForeignKey(DetalleTabla, on_delete=models.RESTRICT, limit_choices_to=Q(tabla__tabla='sectores'), help_text="Sector social al que pertenece el indicador.", related_name='indicadores_sectores', related_query_name='indicador_sector')
	formula = models.CharField('Fórmula de Cálculo', max_length=50, help_text="Fórmula con la que se calcula el valor del indicador.")
	metrica = models.CharField('Métrica de Valoración', max_length=25, choices=[('Cre', 'Creciente'), ('Dec', 'Decreciente')], help_text="Métrica con que se analizan los valores del indicador.")
	tipo_valor = models.ForeignKey(DetalleTabla, on_delete=models.SET_NULL, limit_choices_to=Q(tabla__tabla='tipos_valor'), null=True, related_name='indicadores_tipos_valores', related_query_name='indicador_tipo_valor', help_text='Tipo de valor del indicador.')
	periodicidad = models.ForeignKey(DetalleTabla, on_delete=models.SET_NULL, limit_choices_to=Q(tabla__tabla='periodos'), null=True, related_name='indicadores_periodos', related_query_name='indicador_periodo')
	portada = models.ImageField('Portada', upload_to='suir/indicadores/img/', null=True)
	ficha = models.FileField('Ficha Técnica', upload_to='suir/indicadores/docs/', help_text="Documento en Formato PDF", null=True, blank=True)
	tags = models.TextField(null=True, blank=True)
	entidad = models.ForeignKey(Entidad, on_delete=models.RESTRICT, help_text='Entidad responsable del seguimiento del indicador.')
	colaboradores = models.ManyToManyField('Institucion', help_text='Instituciones colaboradoras en la recolección de datos para el indicador.')
	responsable = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='indicadores_responsables', related_query_name='indicador_responsable')
	desagregaciones = models.ManyToManyField(DetalleTabla, help_text='Desagregaciones del indicador', related_name='+', limit_choices_to=Q(tabla__tabla='desagregaciones'))
	fuente = models.CharField('Fuente de datos', max_length=150, help_text="Fuente donde se obtienen los datos/valores del indicador.")
	marco = models.CharField('Marco legal', max_length=150, help_text="Marco legal que respalda el seguimiento del indicador.")
	estado = models.ForeignKey(DetalleTabla, on_delete=models.SET_NULL, limit_choices_to=Q(tabla__tabla='estados_pub'), help_text="Posibles valores: borrador, pendiente, publicado", null=True, related_name='indicadores_estados', related_query_name='indicador_estado')
	version = models.PositiveSmallIntegerField()
	activo = models.BooleanField()
	seguimiento = models.BooleanField('En seguimiento', help_text='El indicador está siendo monitoreado y se recogen datos del mismo.')
	creador = models.ForeignKey(User, on_delete=models.RESTRICT, related_name='indicadores_creadores', related_query_name='indicador_creador')

	def __str__(self):
		return self.titulo.upper()

	def get_absolute_url(self):
		return reverse('detalle_indicador', kwargs={'pk':self.pk})

	class Meta:
		ordering = ['-seguimiento', 'sector', 'titulo']
		verbose_name_plural = 'Indicadores'



class ValorIndicador(SoftDeletionModel, TimestampsModel):
	"""Clase del modelo ValorIndicador""" 
	fecha = models.DateField('Fecha', auto_now_add=True)
	fecha_inicio = models.DateField('Inicio de la captación')
	fecha_final = models.DateField('Final de la captación')
	indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE, limit_choices_to={'activo':True, 'seguimiento':True})
	recolector = models.CharField('Recolector de datos', max_length=50)
	entidad = models.ForeignKey(Entidad, on_delete=models.RESTRICT)
	digitador = models.ForeignKey(User, on_delete=models.RESTRICT, related_name='valores_digitadores', related_query_name='valor_digitador')
	supervisor = models.ForeignKey(User, on_delete=models.RESTRICT, null=True, related_name='valores_supervisores', related_query_name='valor_supervisor')
	codigo_ficha = models.CharField('Código de ficha', max_length=50, null=True, blank=True)
	ficha = models.FileField(upload_to='suir/indicadores/fichas/', help_text='Ficha en formato PDF', null=True, blank=True)
	comunidad = models.ForeignKey(Comunidad, on_delete=models.RESTRICT, default=1, help_text='Comunidad donde se levantó el dato.')
	sexo = models.CharField('Sexo', max_length=1, choices=[('M', 'Masculino'), ('F', 'Femenino')], null=True, blank=True, help_text='Si aplica al tipo de valor del indicador.')
	etnia = models.ForeignKey(DetalleTabla, on_delete=models.RESTRICT, null=True, blank=True, related_name='valores_etnias', related_query_name='valor_etnia')
	rango_edad = models.ForeignKey(DetalleTabla, on_delete=models.RESTRICT, help_text='Rango de edad (si aplica).', null=True, related_name='valores_rangos_edad', related_query_name='valor_rango_edad')
	valor = models.DecimalField('Valor', max_digits=8, decimal_places=2)
	estado = models.ForeignKey(DetalleTabla, on_delete=models.RESTRICT, help_text="Posibles valores: borrador, pendiente, publicado", related_name='valores_estados', related_query_name='valor_estado')

	class Meta:
		ordering = ['indicador', '-fecha']

suir/forms.py
from django import forms
from django.forms import Form, ModelForm
from suir.models import Publicacion, ValorIndicador

# Clases de formularios


# class LoginForm(Form):
# 	"""
# 	Formulario de validación de usuarios
# 	"""
# 	username = models.CharField("Nombre de Usuario", max_length=25)
# 	contrasena = models.CharField("Contraseña", min_length=8, widget=forms.PasswordInput)




class PublicacionForm(ModelForm):

	class Meta:
		model = Publicacion
		exclude = ['slug', 'autor', 'tipo', 'publicado']


class ValorIndicadorForm(ModelForm):

	class Meta:
		model = ValorIndicador
		exclude = ['digitador','supervisor']
		labels = {
			'indicador':'Indicador',
			'entidad':'Entidad',
			'comunidad':'Comunidad',
			'rango_edad':'Rango de edad',
			'estado':'Estado de publicación',
		}

suir/views.py
from django.shortcuts import get_object_or_404, get_list_or_404, render, redirect
from django.db.models import Q
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import View 
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from hitcount.views import HitCountDetailView
from suir.models import *
import datetime


# Create your views here.

PAGINAS = settings.SUIR_CONF['paginas']


# Views

class InicioView(TemplateView):

	template_name = 'suir/inicio.html'

	def get_context_data(self, **kwargs):

		context = super().get_context_data(**kwargs)

		carrusel = Carrusel.objects.filter(activo=True)
		promovidos = Publicacion.objects.filter(carrusel=True)

		min_count = 3
		max_count = 6
		car_count = carrusel.count()
		prom_count = promovidos.count()

		if prom_count > min_count and car_count > min_count:
			carrusel = carrusel.order_by('-id')[:min_count]
			promovidos = promovidos.order_by('-fecha')[:min_count]
		elif prom_count > car_count and car_count <= min_count:
			promovidos = promovidos.order_by('-fecha')[:max_count]
		else:
			carrusel = carrusel.order_by('-id')[:max_count]

		anuncios = Anuncio.objects.filter(activo=True).order_by('-id')[:2]
		noticias = Publicacion.objects.filter(tipo__elemento='noticia', estado__elemento='publicado')[:4]
		informes = Publicacion.objects.filter(tipo__elemento='informe', estado__elemento='publicado')[:4]
		enlaces = LinkExterno.objects.filter(activo=True)[:6]
		redes = LinkRed.objects.filter(activo=True)
		transmision = None

		try:
			transmision = Transmision.objects.latest('inicio')
			tduracion = datetime.timedelta(hours=1)
			tactual = timezone.now()
			print(tactual.tzinfo.utcoffset(None))

			if transmision.final != None:
				if transmision.final < tactual:
					transmision = None 
			else:
				ttranscurrido = transmision.inicio + tduracion
				if ttranscurrido < tactual:
					transmision = None 
		except Transmision.DoesNotExist as e:
			print(e)
			transmision = None
		finally:
			context['transmision'] = transmision

		context['carrusel'] = carrusel
		context['promovidos'] = promovidos
		context['anuncios'] = anuncios
		context['noticias'] = noticias
		context['informes'] = informes
		context['enlaces'] = enlaces
		context['redes'] = redes 
		context['carrusel_count'] = car_count + prom_count
		context['fecha'] = datetime.datetime.now()

		return context


class SuirListView(ListView):

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		paginator = context['paginator']

		enlaces = LinkExterno.objects.filter(activo=True)[:6]
		redes = LinkRed.objects.filter(activo=True)

		context['enlaces'] = enlaces
		context['redes'] = redes 

		context['fecha'] = datetime.datetime.now()

		context['rango_paginas'] = paginator.get_elided_page_range(self.request.GET.get('page',1), on_each_side=3, on_ends=3)

		return context


class SuirDetailView(DetailView):

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		enlaces = LinkExterno.objects.filter(activo=True)[:6]
		redes = LinkRed.objects.filter(activo=True)

		context['enlaces'] = enlaces
		context['redes'] = redes 

		context['fecha'] = datetime.datetime.now()

		return context



class ListaPublicacionesView(SuirListView):
	paginate_by = PAGINAS
	template_name = 'suir/grid_list.html'
	tipo = ''

	def get_queryset(self):
		return Publicacion.objects.filter(tipo__elemento=self.tipo, estado__elemento='publicado')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['tipo'] = self.tipo
	
		return context


class ListaFiltroPublicacionesView(ListaPublicacionesView):

	def get_queryset(self):
		clave = self.request.GET.get('q').strip()

		return Publicacion.objects.filter(Q(titulo__contains=clave) | Q(tags__contains=clave),tipo__elemento=self.tipo, estado__elemento='publicado')


class DetallePublicacionView(HitCountDetailView):
	model = Publicacion
	context_object_name = 'publicacion'
	count_hit = True

	def get_queryset(self):
		slug = self.kwargs['slug']
		return Publicacion.objects.filter(slug=slug)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		enlaces = LinkExterno.objects.filter(activo=True)[:6]
		redes = LinkRed.objects.filter(activo=True)

		context['tipo'] = self.object.tipo.elemento
		context['tags'] = [tag.strip() for tag in  self.get_object().tags.split(',')]
		context['enlaces'] = enlaces
		context['redes'] = redes 
		context['fecha'] = datetime.datetime.now()

		return context




class ListaIndicadoresView(SuirListView):
	paginate_by = PAGINAS
	model = Indicador

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['tipo'] = 'indicador'
		return context


class ListaFiltroIndicadoresView(ListaIndicadoresView):

	def get_queryset(self):
		clave = self.request.GET.get('q').strip()
		return Indicador.objects.filter(Q(titulo__contains=clave) | Q(sector__elemento__startswith=clave) | Q(tags__contains=clave))

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['tipo'] = 'indicador'
		return context


class DetalleIndicadorView(SuirDetailView):
	model = Indicador
	context_object_name = 'indicador'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['tipo'] = 'indicador'
		return context


class DetalleValorView(LoginRequiredMixin, SuirDetailView):

	model = ValorIndicador
	context_object_name = 'valor'

templates/suir/ItemPublicacion.html
{% load static %}

{% load django_bootstrap5 %}

<div class="col-3">
	<div class="card mb-2">
		<img class="card-img-top" src="{{ publicacion.portada.url }}" alt="Portada de publicación">
		<div class="card-body">
			<a href="{{  publicacion.get_absolute_url }}">
				<div class="card-title fs-6">
					{{ publicacion.titulo | upper }}
				</div>
			</a>
		</div>
	</div>
</div>

templates/suir/Pagination.html
{% load django_bootstrap5 %}

{% load bootstrap_icons %}


{% if page_obj.paginator.num_pages > 1 %}

<nav aria-label="Navegación de páginas">
	<ul class="pagination">
		{% if page_obj.has_previous %}
			<li class="page-item">
				<a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-disabled="false">
					{% bs_icon 'chevron-left' %}
				</a>
			</li>
		{% endif %}

		{% for pagina in rango_paginas %}
			{% if not pagina > 0 %}
				{% if pagina == page_obj.number %}
					<li class="page-item active" aria-current="page">
						
				{% else %}
					<li class="page-item">
				{% endif %}
					<a href="?page={{ pagina }}" class="page-link">
							{{ pagina }}
						</a>
					</li>
			{% else %}
				<li class="page-item  disabled">
					<a href="#" class="page-link pe-none">
						{{ pagina }}
					</a>
				</li>
			{% endif %}
		{% endfor %}
		
		{% if page_obj.has_next  %}
			<li class="page-item">
				<a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-disabled="false">
					{% bs_icon 'chevron-right' %}
				</a>
			</li>
		{% endif %}
	</ul>
</nav>

{% endif %}

templates/suir/SuirCarousel.html
{% load static %}

{% if carrusel and carrusel.count > 0 or promovidos and promovidos.count > 0 %}
<div class="container">
	<div class="row">
		<div class="col-8 mx-auto">
			<div
				id="suirCarousel" 
				class="carousel slide u-margin-top-big"
				data-bs-ride="carousel"
			>
				<div class="carousel-indicators">
					{% with ''|center:carrusel_count as range %}
						{% for _ in range %}
							<button type="button" data-bs-target="#suirCarousel" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.counter == 1 %} class="active" {% endif %}aria-label="Slide {{ forloop.counter0 }}"></button>
						{% endfor %}
					{% endwith %}
				</div>
				<div class="carousel-inner">
					{% if carrusel and carrusel.count > 0 %}
						{% for slide in carrusel %}
							<div class="carousel-item{% if forloop.counter == 1 %} active{% endif %}">
								<img class="d-block w-100" src="{{ slide.imagen.url }}" alt="{{ slide.titulo | lower }}">
								<div class="carousel-caption text-end d-none d-md-block">
									<h5>{{ slide.titulo | upper }}</h5>
									{% if slide.descripcion %}
										<p>{{ slide.descripcion | lower | capfirst }}</p> 
									{% endif %}
								</div>
							</div>
						{% endfor %}
					{% endif %}
					{% if promovidos and promovidos.count > 0 %}
						{% for slide in promovidos %}
							<div class="carousel-item{% if not carrusel or carrusel.count == 0 %} active{% endif %}">
								<img class="d-block w-100" src="{{ slide.portada.url }}" alt="{{ slide.titulo | lower }}">
								<div class="carousel-caption text-end d-none d-md-block">
									<a class="text-decoration-none text-reset" href="{{ slide.get_absolute_url }}">
										<h5>{{ slide.titulo | upper }}</h5>
									</a>
									
								</div>
							</div>
						{% endfor %}
					{% endif %}
				</div>
				<button class="carousel-control-prev" type="button" data-bs-target="#suirCarousel" data-bs-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="visually-hidden">Anterior</span>
				</button>
				<button class="carousel-control-next" type="button" data-bs-target="#suirCarousel" data-bs-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="visually-hidden">Siguiente</span>
				</button>
			</div>
		</div>
	</div>
</div>
{% endif %}

templates/suir/SuirFooter.html
{% load bootstrap_icons %}
<footer class="footer">
    <div class="container footer-container">
        <div class="row align-items-center footer-row">
            <div class="footer-nav col-md-4 col-sm-6 col-xs-12 text-center">
                {% if enlaces %}
                    <ul class="nav">
                    	<!-- If has links, show inline links -->
                    	<!-- la url se obtiene de un objeto de lista de links -->
                        {% for enlace in enlaces %}
                            <li class="footer-nav__el nav-item">
                                <a href="{{ enlace.url }}" class="footer-nav__el-link nav-link" target="_blank">{{ enlace.texto }}</a>
                            </li>
                        {% endfor %}
                            
                    </ul>
                {% endif %}
            </div>
            <div class="hidden-xs hidden-sm col-md-4 text-center">
                <div class="footer-copyright">
                    <p class="footer-copyright__text">Todos los derechos reservados {{ fecha | date:'Y' }} &copy;
                        <span class="meta-separator">|</span>
                        <a href="#">Condiciones y Políticas</a>
                    </p>
                </div>
            </div>
            <div class="hidden-xs col-sm-6 col-md-3 text-center">
                <ul class="nav links footer-social">
					<!-- Si hay información general, generar los enlaces a sitios relacionados -->
					<!-- la url se toma de un campo del objeto generalInfo para cada sitio relacionado. Ej. generalInfo.facebook -->
                    {% for redsocial in redes %}
                        <li class="nav-item">
                            <a href="{{ redsocial.url }}" target="_blank" class="nav-link">
                                {% bs_icon redsocial.red %}
                            </a>
                        </li>
                    {% endfor %}
                    
                </ul>
            </div>
        </div>
   </div>
</footer>

templates/suir/indicador_list.html
{% extends './base.html' %}

{% load django_bootstrap5 %}

{% load bootstrap_icons %}

{% block header %}
	{% include './SuirHeader.html' with seccion=tipo %}
{% endblock %}

{% block content %}
<div class="container mt-5">
	<div class="row">
		<div class="col">
			<h1 class="u-bg-secondary section-header">INDICADORES &#10022;</h1>
		</div>
	</div>
	
	{% if object_list and object_list.count > 0 %}
	<div class="row clearfix mt-3">
		<nav>
			<form class="d-flex search-form mx-2" action="{% url 'buscar_indicadores' %}" method="get">
				<input type="search" class="form-control me-2" name="q" placeholder="Buscar" aria-label="buscar">
				<button class="btn btn-outline-success" data-toggle="tooltip" data-placement="bottom" title="Buscar">
					{% bs_icon 'search' %}
				</button>
			</form>
		</nav>
	</div>
	<div class="row">
		<div class="col-10">
			<table class="table table-striped">
				<thead class="thead-light">
					<tr>
						<th>SECTOR</th>
						<th>INDICADOR</th>
						<th>DATOS</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for indicador in object_list %}
					<tr>
						<td class="w-25">{{ indicador.sector.elemento | upper }}</td>
						<td class="w-50">{{ indicador.titulo | upper }}</td>
						<td class="w-auto">
							{% if indicador.valorindicador_set.count > 0 %}
								{% bs_icon 'hand-thumbs-up-fill' extra_classes="text-success" %}
							{% else %}
								{% bs_icon 'hand-thumbs-down-fill' extra_classes="text-danger" %}
							{% endif %}
						</td>
						<td class="w-auto">
							<a data-toggle="tooltip" data-placement="top" title="Ver" href="{{ indicador.get_absolute_url }}" class="btn btn-outline-success">
								{% bs_icon 'eye' %}
							</a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			{% include './Pagination.html' with page_obj=page_obj rango_paginas=rango_paginas %}
		</div>
	</div>
	{% else %}
	<div class="row mt-3">
		<div class="col-8 mx-auto">
			<div class="alert alert-warning">
				NO HAY REGISTROS. REGRESAR AL <a href="{% url 'inicio' %}">INICIO</a>
			</div>
		</div>
	</div>
	{% endif %}
</div>
{% endblock %}

{% block footer %}
	{% include './SuirFooter.html' %}
{% endblock %}